'use client';
import { useState } from 'react';
import { BookOpen, ChevronRight, Headphones, Home, LogOut, Menu, Mic, PenLine, Settings, Sparkles, Target, UserRound, X } from 'lucide-react';

const nav = [{ icon: Home, label: 'Bosh sahifa' }, { icon: Mic, label: 'Speaking' }, { icon: PenLine, label: 'Writing' }, { icon: BookOpen, label: 'Reading' }, { icon: Headphones, label: 'Listening' }];
const cards = [
  { title: 'Speaking practice', Uzbek: 'AI ustoz bilan gaplashing', icon: Mic, tone: 'bg-[#e9e4ff]', progress: 68 },
  { title: 'Writing checker', Uzbek: 'Essengizga band baho oling', icon: PenLine, tone: 'bg-[#ffe3da]', progress: 42 },
  { title: 'Reading trainer', Uzbek: 'Matnlarni o‘qib mashq qiling', icon: BookOpen, tone: 'bg-[#dff7eb]', progress: 31 },
  { title: 'Listening lab', Uzbek: 'Eshitish qobiliyatingizni oshiring', icon: Headphones, tone: 'bg-[#fff0c9]', progress: 55 },
];
export default function Dashboard() {
  const [open, setOpen] = useState(false); const [tab, setTab] = useState('Bosh sahifa');
  return <div className="min-h-screen bg-[#f8faf9] text-ink">
    <button onClick={() => setOpen(!open)} className="fixed left-4 top-4 z-30 rounded-xl bg-ink p-3 text-white md:hidden">{open?<X/>:<Menu/>}</button>
    <aside className={`${open?'translate-x-0':'-translate-x-full'} fixed z-20 flex h-screen w-72 flex-col border-r bg-white p-6 transition md:translate-x-0`}>
      <div className="mb-12 flex items-center gap-2 text-2xl font-black"><span className="grid h-9 w-9 place-items-center rounded-xl bg-ink text-sm text-white">9</span>ielts<span className="text-violet">.uz</span></div>
      <div className="mb-4 text-xs font-bold uppercase tracking-widest text-slate-400">Menyu</div>
      <div className="space-y-2">{nav.map(({icon: Icon,label}) => <button key={label} onClick={()=>{setTab(label);setOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-bold ${tab===label?'bg-[#eeeaff] text-violet':'text-slate-500 hover:bg-slate-50'}`}><Icon size={19}/>{label}{label==='Speaking'&&<span className="ml-auto rounded-full bg-violet px-2 py-0.5 text-[10px] text-white">AI</span>}</button>)}</div>
      <div className="mt-auto space-y-2 border-t pt-5"><button className="flex w-full items-center gap-3 px-4 py-3 text-sm font-bold text-slate-500"><Settings size={19}/>Sozlamalar</button><button className="flex w-full items-center gap-3 px-4 py-3 text-sm font-bold text-slate-500"><LogOut size={19}/>Chiqish</button></div>
    </aside>
    <main className="md:ml-72"><header className="flex items-center justify-between border-b bg-white px-6 py-5 md:px-10"><div><p className="text-sm text-slate-500">Payshanba, 17-sentabr</p><h1 className="text-2xl font-black">Xush kelibsiz, Habibulloh! 👋</h1></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><b className="block text-sm">Habibulloh</b><span className="text-xs text-slate-400">Beginner</span></div><div className="grid h-11 w-11 place-items-center rounded-full bg-[#b9f4dc] font-black">H</div></div></header>
      <div className="mx-auto max-w-6xl px-6 py-8 md:px-10"><section className="relative overflow-hidden rounded-3xl bg-ink p-7 text-white md:p-10"><div className="relative z-10 max-w-xl"><div className="mb-4 flex items-center gap-2 text-sm font-bold text-mint"><Sparkles size={17}/> BUGUNGI MAQSAD</div><h2 className="text-3xl font-black md:text-4xl">IELTS 9.0 ga bir qadam yaqinroq bo‘ling.</h2><p className="mt-3 text-sm leading-6 text-slate-300">Har kuni 20 daqiqa mashq qiling va natijangizni tezroq yaxshilang.</p><button className="mt-6 flex items-center gap-2 rounded-xl bg-mint px-5 py-3 text-sm font-black text-ink">Mashqni boshlash <ChevronRight size={17}/></button></div><div className="absolute -right-12 -top-20 h-80 w-80 rounded-full border-[40px] border-violet/40"/><div className="absolute right-12 top-12 hidden rounded-2xl bg-white/10 p-5 backdrop-blur md:block"><Target className="mb-3 text-mint"/><div className="text-xs text-slate-300">Hozirgi daraja</div><b className="text-3xl">Band 5.5</b></div></section>
        <div className="mt-8 flex items-end justify-between"><div><p className="text-sm font-bold text-violet">IELTS KURSLARI</p><h2 className="mt-1 text-2xl font-black">Ko‘nikmalaringizni rivojlantiring</h2></div><button className="hidden text-sm font-bold text-violet md:block">Barchasi <ChevronRight className="inline" size={16}/></button></div>
        <div className="mt-5 grid gap-4 sm:grid-cols-2">{cards.map(({title, Uzbek, icon:Icon,tone,progress})=><button key={title} className={`${tone} group rounded-2xl p-5 text-left transition hover:-translate-y-1`}><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white"><Icon size={21}/></div><ChevronRight className="text-slate-500 transition group-hover:translate-x-1" size={19}/></div><h3 className="mt-8 font-black">{title}</h3><p className="mt-1 text-sm text-slate-600">{Uzbek}</p><div className="mt-5 h-1.5 rounded-full bg-white/70"><div className="h-full rounded-full bg-ink" style={{width:`${progress}%`}}/></div><p className="mt-2 text-xs font-bold text-slate-500">{progress}% tugallandi</p></button>)}</div>
        <section className="mt-8 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-2xl border bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-black">Haftalik faollik</h2><p className="mt-1 text-sm text-slate-500">Bu hafta 3 soat 25 daqiqa</p></div><span className="rounded-lg bg-[#eeeaff] px-3 py-2 text-xs font-bold text-violet">Bu hafta</span></div><div className="mt-8 flex h-32 items-end justify-between gap-3">{['Du','Se','Ch','Pa','Ju','Sh','Ya'].map((d,i)=><div key={d} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className={`w-full rounded-t-lg ${i===4?'bg-violet':'bg-[#d9f4e9]'}`} style={{height:`${[35,55,42,72,88,30,18][i]}%`}}/><span className="text-xs text-slate-400">{d}</span></div>)}</div></div><div className="rounded-2xl bg-[#fff0c9] p-6"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white"><UserRound size={21}/></div><h3 className="mt-6 font-black">Profilingiz</h3><p className="mt-2 text-sm leading-6 text-slate-600">Darajangizni aniqlash testini ishlang.</p><button className="mt-5 flex items-center gap-1 text-sm font-black">Testni boshlash <ChevronRight size={16}/></button></div></section>
      </div>
    </main>
  </div>
}
